openapi: 3.1.0
info:
  version: 1.0.0
  title: Your App Title
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Your app description
tags:
  - name: Contacts
    description: API for managing contacts
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-7-9tw1.onrender.com/api-docs/#/
paths:
  /contacts/{contactId}:
  get:
    $ref: '../swagger/paths/contacts/contactID/get.yaml'
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
    patch:
      $ref: '../swagger/paths/contacts/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/delete.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    contact:
      $ref: '../swagger/components/schemas/contact.yaml'
    user:
      $ref: '../swagger/components/schemas/user.yaml'
  responses:
    success:
      $ref: '../swagger/components/responses/success.yaml'
    notFound:
      $ref: '../swagger/components/responses/notFound.yaml'
